name: hacs

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "30 4 * * *"

permissions:
  contents: read

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration
